site_name: Ops Journal
docs_dir: docs          # child folder
site_dir: site          # output folder (must not be inside docs/)
theme:
  name: material
nav:
  - Home: index.md
  - Logs:
      - Logs: logs/
  - Learning:
      - Learning: learning/
